name: Build Troublescope

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y fuse3 libfuse3-dev

      - name: Build Troublescope binary
        run: |
          make

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: troublescope-binary
          path: ./libtroublescope.so
